### PR TITLE
Frame clause for windows

### PR DESCRIPTION
**Pull request by Anber**
The last part of WINDOW clause.

### CODE REVIEW

**Comment by Anber** [comment]
@josevalim, are you sure that repository splitting was a good idea? :)
Maybe monorepo will be a better solution? At least CI will be able to check PRs which affects more than one package.

**Comment by josevalim** [comment]
Since the parent one was merged, we are not ready to go with this one. :)

**Comment by josevalim** [comment]
Sorry, I meant to say we are **now** ready to go with this one!

**Comment by Anber** [comment]
@josevalim what’s wrong with this one? :)

**Comment by Anber** [comment]
I can push something to trigger CI :)

**Comment by josevalim** [comment]
Wait, you have already updated it. Gah, I am sorry. Too slow today.

**Comment by josevalim** [comment]
@Anber we need to bring ecto as a git dependnecy for the CI to pass. Can you please update it? This should be enough:

    {:ecto, github: "elixir-lang/ecto"}

**Comment by josevalim** [comment]
Ah, other things are broken in master. I will merge and fix it then. :) Thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
