### PR TITLE
Support column renames in MySQL adapter

### PR DESCRIPTION
**Pull request by wojtekmach**
Ref elixir-ecto/ecto#2601

Tested locally by running `ECTO_ADAPTER=mysql mix test --include rename_column`

### CODE REVIEW

**Comment by wojtekmach** [comment]
The only thing left is to enable this test on CI for MySQL 8.0, I'll look into that.

**Comment by wojtekmach** [comment]
@josevalim can we merge this as is? I have a separate branch for enabling mysql 8 on CI as it's a bit more involved.

**Comment by josevalim** [comment]
We need a test in test/ecto/adapters/mysql_test.exs and we should be good to go!

**Comment by josevalim** [comment]
Closing in favor of the other PR.

**Pull request closed without merging**
