### PR TITLE
Suppress query logs in mix ecto.load when quiet flag is given.

### PR DESCRIPTION
**Pull request by greg-rychlewski**
Closes https://github.com/elixir-ecto/ecto_sql/issues/501

Since it's not performing any migrations this should quiet all the logs.

### CODE REVIEW

**Review by josevalim — APPROVED** [review]
Do we need similar change for dump?

**Comment by greg-rychlewski** [comment]
Sorry I realized I screwed up. The log option has to go into this: `&Ecto.Adapters.SQL.table_exists?/2`

But then if anyone's using a custom function it will break...

**Comment by greg-rychlewski** [comment]
Maybe checking the arity of the function and passing opts if it is 3?

**Comment by greg-rychlewski** [comment]
It doesn't look like we need to worry about dump. It is calling the drivers directly which are not logging the queries.

**Review by v0idpwn — APPROVED** [review]

**Pull request merged**
