### PR TITLE
Remove skip_transaction opts to match Ecto changes

### PR DESCRIPTION
**Pull request by dkulchenko**
Following up on elixir-ecto/ecto@47dd10d33.

### CODE REVIEW

**Comment by josevalim** [comment]
I would keep them for now because merging this means we would support only
Ecto master. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by dkulchenko** [comment]
Fair enough! Closing for now :)

**Comment by josevalim** [comment]
Let me just check something (GitHub actions integration).

**Comment by josevalim** [comment]
Doesn’t work it seems :(

**Pull request closed without merging**
