### PR TITLE
Add -v option to docs

### PR DESCRIPTION
**Pull request by acontreras89**

### CODE REVIEW

**Comment by josevalim** [comment]
Looking at the code we don't seem to support such option, do we? 🤔

**Comment by acontreras89** [comment]
I didn't even try, but this option was already [included in the docs](https://github.com/elixir-ecto/ecto_sql/blob/5ceec51c617b00fe68b07c5db364ccac72053992/lib/mix/tasks/ecto.migrate.ex#L67).

**Comment by wojtekmach** [comment]
Yeah, we don't actually have such option, I went ahead and remove it from docs. Good find :)

**Comment by acontreras89** [comment]
Good :)

**Pull request closed without merging**
