### PR TITLE
add to Ecto.Migration.Runner repo_name helper function

### PR DESCRIPTION
**Pull request by bartekupartek**
I realised that `Process.put(:repo_name, current_tenant_repo_name)` doesn't work during migrations, so it might be helpful to get `repo_name` directly from migration runner process instead of
```elixir
case Process.get(:ecto_migration) do
  %{runner: runner} ->
    Agent.get(runner, & &1.repo_name)
  nil -> nil
end
```

### CODE REVIEW

**Comment by josevalim** [comment]
Can we have a small test? Thanks! You can see where the other ones are tested.

**Comment by bartekupartek** [comment]
I think it should be as meta, when I use this function and runner is `nil` then it will raise error as it turned out on firsthand.

**Comment by josevalim** [comment]
@bartekupartek sorry? :)

**Comment by bartekupartek** [comment]
sorry, I was wrong, I don't see any tests for similar helper methods

**Comment by josevalim** [comment]
@bartekupartek I think it is because we use them internally. Since we don't use this one internally, I think a test would be welcome! :)

**Comment by bartekupartek** [comment]
automated tests has been added

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
