### PR TITLE
Add :prefix option to references/2

### LINKED ISSUE #51: Migration.references/2 should support :prefix
I would expect the following to create a cross-schema reference:

```elixir
create table(:comments, prefix: :child_app) do
  add :user_id, references("parent.users")
end
```

Alternatively:

```elixir
create table(:comments, prefix: :child_app) do
  add :user_id, references("users", prefix: :parent)
end
```

### PR DESCRIPTION
**Pull request by whitepaperclip**
Fixes #51 for Postgres.

### CODE REVIEW

**Comment by josevalim** [comment]
Can you please add the same for MySQL and tests at
test/ecto/adapters/*_test.exs? Thanks!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whitepaperclip** [comment]
On it!

**Comment by whitepaperclip** [comment]
@josevalim Is there a timeline for running this through `mix format`?

**Comment by josevalim** [comment]
Eventually :P
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whitepaperclip** [comment]
@josevalim Done!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
